name: Run tests

on:
  push:

permissions:
  contents: read

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.20.4'
          cache: true
      - name: Run go tests
        run: |
          go test ./...
